/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BrickButton: (typeof import('./../components/BrickButton.vue'))['default'];
    BrickCard: (typeof import('./../components/BrickCard.vue'))['default'];
  }
}
